# Copyright © 2020 Interplanetary Database Association e.V.,
# Planetmint and IPDB software contributors.
# SPDX-License-Identifier: (Apache-2.0 AND CC-BY-4.0)
# Code is Apache-2.0 and docs are CC-BY-4.0

---
- name: Building Planetmint Docker
  docker_image:
    name: "{{ planetmint_image_name }}"
    state: build
    tag: "{{planetmint_image_tag }}"
    dockerfile: Dockerfile-alpine
    path: "{{ home_dir }}/planetmint"
    nocache: yes
    buildargs:
      backend: localmongodb
  when: stack_type|lower == "docker" or stack_type|lower == "cloud"
  tags: [planetmint]

- name: Start Planetmint Docker
  docker_container:
    name: "{{ planetmint_docker_name }}{{ item }}"
    image: "{{ planetmint_image_name }}:{{ planetmint_image_tag }}"
    hostname: "{{ planetmint_docker_name }}{{ item }}"
    detach: true
    network_mode: bridge
    networks:
      - name: "{{ planetmint_docker_net }}"
    env:
      PLANETMINT_DATABASE_BACKEND: "localmongodb"
      PLANETMINT_DATABASE_HOST: "{{ mongodb_docker_name }}{{ item }}"
      PLANETMINT_DATABASE_PORT: "27017"
      PLANETMINT_SERVER_BIND: "0.0.0.0:9984"
      PLANETMINT_WSSERVER_HOST: "0.0.0.0"
      PLANETMINT_TENDERMINT_HOST: "{{ tendermint_docker_name }}{{ item }}"
      PLANETMINT_TENDERMINT_PORT: "{{ planetmint_tendermint_port | string }}"
    published_ports:
      - "{{ planetmint_default_server_port }}"
      - "{{ planetmint_default_ws_port }}"
      - "{{ tendermint_abci_port }}"
    restart_policy: always
    state: started
    command: planetmint -l DEBUG start
  with_sequence: start=1 end="{{ stack_size|int }}" stride=1
  when: stack_type|lower == "docker" or stack_type|lower == "cloud"
  tags: [planetmint]

- import_tasks: debian.yml
  when: stack_type == "local" and (distribution_name == "debian" or distribution_name == "ubuntu")
  tags: [planetmint]

- import_tasks: centos.yml
  when: stack_type|lower == "local" and (distribution_name == "centos" or distribution_name == "red hat enterprise linux")
  tags: [planetmint]

- import_tasks: fedora.yml
  when: stack_type|lower == "local" and (distribution_name == "fedora")
  tags: [planetmint]

- import_tasks: common.yml
  when: stack_type|lower == "local"
  tags: [planetmint]