# Copyright © 2020 Interplanetary Database Association e.V.,
# Planetmint and IPDB software contributors.
# SPDX-License-Identifier: (Apache-2.0 AND CC-BY-4.0)
# Code is Apache-2.0 and docs are CC-BY-4.0

---
- name: Install dependencies py39 | yum
  yum:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - "yum-utils"
    - "https://centos7.iuscommunity.org/ius-release.rpm"
  tags: [py39]

- name: Install py39 | yum
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "python39u"
    - "python39u-pip"
    - "python39u-devel"
  tags: [py39]